### PR TITLE
Feat/add media map

### PR DESCRIPTION
**Pull request by Peterlollo**
- adds `/media-map` showing a map hosted in the repo: `hyperobjekt/seda-media-map`
- `/media-map` also displays a table of national news stories
- Removes `node_modules` folder from git tracking

### CODE REVIEW

**Comment by amygroshek** [comment]
@Peterlollo This looks great. Looks like you were able to utilize the file org & frontmatter system for our Hugo projects just fine. I like the cache-busting strategy on the JS file. 

I'm showing an error in IE11 regarding Object support for 'startswith' (missing polyfill). I think that this is an interface mostly for the client to track this info, not to show to site visitors, and we don't need to be extremely concerned about browsers support. But we do have a babel transpile step set up for this repo, to preprocess the javascript files. It's documented in the readme. And if you add this file to that process it should fix this issue. Sometimes academics can lag in browser adoption, for various reasons.

I'm also getting a contrast issue and a few other semantic issues when I run an automated a11y test tool on the page. I'm able to navigate the controls pretty well with a keyboard, though, so that's great. I don't know what the hourly budget is for this, or how much @james-minton wants you to be concerned with these aspects.

[media-map-pa11y.txt](https://github.com/Hyperobjekt/seda-site/files/3791805/media-map-pa11y.txt)

I'll leave any stylistic concerns to @james-minton.

**Comment by amygroshek** [comment]
@Peterlollo @james-minton Looks like even after transpile and adding a polyfill there's still one issue and it's coming from a js file loaded from mapbox... IDK what approach we want to take there. At any rate, our IE11 JS issue is now resolved. 

SCRIPT1014: Invalid character
main.js (44,13)

Screen Shot 2019-11-01 at 1 21 06 AM

**Comment by Peterlollo** [comment]
@amygroshek the `main.js` file is actually in another one of our repo's: `hyperobjekt/seda-media-map`, so we can probably fix this.

**Comment by Peterlollo** [comment]
Looking into it now.

**Comment by Peterlollo** [comment]
@amygroshek @james-minton the errors should be fixed now. There was no transpiler for the es6 in the other repo, so I swapped it out.

**Pull request merged**
